import type { Metadata } from "next";

import { BakeryPage } from "./bakery/BakeryPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return <BakeryPage />;
}
