name: Website CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development
    paths:
      - "apps/website/**"
      - "packages/theme/**"
      - "packages/shared/**"
  push:
    branches:
      - main
      - development
    paths:
      - "apps/website/**"
      - "packages/theme/**"
      - "packages/shared/**"

jobs:
  linting:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm website install

      - name: Lint
        run: pnpm website run lint

  build:
    name: Astro Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm website install

      - name: Run build
        run: pnpm website run build

  # test:
  #   name: Playwright Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8.8.0

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: "pnpm"

  #     - name: Install Dependencies
  #       run: pnpm website install

  #     - name: Run build
  #       run: pnpm website run build

  #     - name: Install Playwright Browsers
  #       run: pnpm site playwright install --with-deps

  #     - name: Run Playwright tests
  #       run: pnpm site playwright test

  #     - uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: apps/site/playwright-report/
  #         retention-days: 30
